Musa
jdxxmahmud/library-management-system pull request #8
Opened 2023-10-11 16:31 UTC by dadyymusa

[1]Changes made in previous db_models and entities.

[2]New models created:
    author_model.py
    staff_model.py
    student_model.py

2023-10-11 23:18 UTC, jdxxmahmud commented on src/db_models/order_model.py
line 14?

2023-10-11 23:18 UTC, jdxxmahmud commented on src/db_models/author_model.py
line 14: I don't think that's how enum should be added

2023-10-11 23:19 UTC, jdxxmahmud commented on src/db_models/orderBook_model.py
change table name

2023-10-11 23:19 UTC, jdxxmahmud commented on src/entities/order.py
line 11

2023-10-11 23:20 UTC, jdxxmahmud requested changes
Make the suggested changes

2023-10-11 23:21 UTC, closed without merging

2023-10-12 13:47 UTC, dadyymusa commented on src/db_models/author_model.py
not  RESOLVED